apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openshift-collector-data
  labels:
    app: openshift-collector
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
